services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: l5teste
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
